defaults:
- /labutils/dlcconfig@_here_
- common
- _self_

name: example-dlc
sessions:
# chewing rig 2
- name: 20231031_B6-B20-B21-B26-B31-B32-B33_chew_rig2
  concat_videos: true # old style preprocessing
