[project]
name = "cheese3d-annotator"
version = "0.1.0"
description = "Napari plugin for picking frames and annotating mouse faces in Cheese3D."
authors = [
    { name = "Hou Lab", email = "the.hou.lab@gmail.com"},
    { name = "Kyle Daruwalla", email = "daruwal@cshl.edu"},
    { name = "Rubin Zhao", email = "rzhao@cshl.edu"}
]
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "tables",
    "pandas",
    "napari",
    "napari-video",
    "magicgui",
    "numpy",
    "scikit-image",
    "imageio",
    "qtpy",
    "PyQt5",
    "pyqtgraph"
]

[project.entry-points."napari.manifest"]
cheese3d_annotator = "cheese3d_annotator:napari.yaml"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["cheese3d_annotator"]

[tool.hatch.metadata]
allow-direct-references = true
