[workspace]
name = "cheese3d"
channels = ["conda-forge", "nvidia", "apple"]
platforms = ["linux-64", "osx-arm64"]

[environments]
docs = { features = ["docs"] }

[tasks]
docs = "cd docs && pixi run -e docs sphinx-build -b html source _build/html"
docs-serve = "cd docs && pixi run -e docs sphinx-autobuild --port 8090 -b html source _build/html"

[host-dependencies]
python = "3.10.*"

[dependencies]
c-compiler = "*"
cxx-compiler = "*"
ffmpeg = "==4.4.1"
av = "==9.2.0"

[pypi-dependencies]
# cheese3d-annotator = { path = "packages/cheese3d-annotator", editable = true }
cheese3d = { path = "packages/cheese3d", editable = true }

[target.linux-64.dependencies]
cudatoolkit = "11.7.*"
cudnn = "8.*"

[target.linux-64.pypi-dependencies]
blosc2 = "*"
tensorflow = "==2.10.*"
jax = { version = ">=0.4, <0.5", extras = ["cuda12_pip"] }
deeplabcut = { git = "https://github.com/Hou-Lab-CSHL/DeepLabCut.git", extras = ["tf"] }

[target.osx-arm64.dependencies]
tensorflow-deps = "*"
hdf5 = "*"
pytables = "*"

[target.osx-arm64.pypi-dependencies]
tensorflow-macos = "==2.10.*"
tensorflow-metal = "==0.6.*"
jax = { version = ">=0.4, <0.5", extras = ["cpu"] }
deeplabcut = { git = "https://github.com/Hou-Lab-CSHL/DeepLabCut.git", extras = ["apple_mchips"] }

[feature.docs.pypi-dependencies]
sphinx = ">=7.2.0,<8.0.0"
sphinx-autodoc-typehints = ">=1.25.0,<2.0.0"
myst-parser = ">=2.0.0,<3.0.0"
nbsphinx = ">=0.9.0,<1.0.0"
sphinx-autobuild = ">=2024.10.3,<2025"
sphinx-book-theme = ">=1.1.4,<2"
sphinxemoji = ">=0.3.1,<0.4"
