[workspace]
name = "cheese3d"
channels = ["conda-forge", "apple"]
platforms = ["linux-64", "osx-arm64"]

[environments]
default = { features = ["dlc"] }
docs = { features = ["docs"] }
dev = { features = ["dev"] }
dev-dlc = { features = ["dev", "dlc"] }
dev-lp = { features = ["dev", "lp-cu12"] }
dev-lp-cu13 = { features = ["dev", "lp-cu13"] }
lp = { features = ["lp-cu12"] }
lp-cu13 = { features = ["lp-cu13"] }

[tasks.build]
args = [ "name" ]
cmd = "pixi run uv build packages/{{ name }}"

[tasks.build-all]
depends-on = [
    { task = "build", args = ["cheese3d-annotator"] },
    { task = "build", args = ["cheese3d"] }
]

[tasks.publish]
args = [ "name", "token", { arg = "index", default = "pypi" }]
cmd = "cd packages/{{ name }} && pixi run uv publish --index {{ index }} --token {{ token }}"
depends-on = [{ task = "build", args = ["{{ name }}"]}]

[tasks.publish-ci]
args = [ "name", { arg = "index", default = "pypi" }]
cmd = "cd packages/{{ name }} && pixi run uv publish --index {{ index }}"
depends-on = [{ task = "build", args = ["{{ name }}"]}]

[tasks.docs]
cmd = "cd docs && pixi run -e docs sphinx-build -b html source _build/html"

[tasks.docs-serve]
cmd = "cd docs && pixi run -e docs sphinx-autobuild --port 8090 -b html source _build/html"

[tasks.test]
cmd = "cd packages/cheese3d && pixi run -e dev pytest"

[tasks.test-subset]
args = ["group"]
cmd = "cd packages/cheese3d && pixi run -e dev pytest -m {{ group }}"

[tasks.test-cov]
cmd = "cd packages/cheese3d && pixi run -e dev pytest --cov=cheese3d --cov-report=html"

[activation.env]
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
PYTHONNOUSERSITE = "1"

[dependencies]
python = "3.11.*"
uv = ">=0.11.11,<0.12"
c-compiler = "*"
cxx-compiler = "*"
ffmpeg = ">=5.1.2"
av = ">=10.0.0"
pillow = ">=9.0.0,<12.0.0"

[pypi-dependencies]
cheese3d_annotator = { path = "packages/cheese3d-annotator", editable = true }
cheese3d = { path = "packages/cheese3d", editable = true }

# [target.linux-64.dependencies]
# cudatoolkit = "11.7.*"
# cudnn = "8.*"

[feature.docs.pypi-dependencies]
sphinx = ">=7.2.0,<8.0.0"
sphinx-autodoc-typehints = ">=1.25.0,<2.0.0"
myst-parser = ">=2.0.0,<3.0.0"
nbsphinx = ">=0.9.0,<1.0.0"
sphinx-autobuild = ">=2024.10.3,<2025"
sphinx-book-theme = ">=1.1.4,<2"
sphinxemoji = ">=0.3.1,<0.4"

[feature.dev.pypi-dependencies]
textual-dev = "*"
pytest = ">=7.4.0,<9.0.0"
pytest-cov = ">=4.1.0,<6.0.0"

[feature.dlc.pypi-dependencies]
cheese3d = { path = "packages/cheese3d", editable = true, extras = ["dlc", "cuda12"] }

# [feature.dlc-cu12.pypi-options]
# extra-index-urls = ["https://download.pytorch.org/whl/cu126"]

[feature.dlc.constraints]
numpy = "<2.0.0"

[feature.lp-cu12.pypi-dependencies]
cheese3d = { path = "packages/cheese3d", editable = true, extras = ["lp", "cuda12"] }

# [feature.lp-cu12.pypi-options]
# extra-index-urls = ["https://download.pytorch.org/whl/cu126"]

[feature.lp-cu13.pypi-dependencies]
cheese3d = { path = "packages/cheese3d", editable = true, extras = ["lp", "cuda13"] }
