# the find_video function is from cheese3d.configutils.find_video
# see the docstring for more info

# to set a crop / extra crop do
#
# crop: [xstart, xend, ystart, yend]
# extra_crops:
#   led: [xstart, xend, ystart, yend]
#
# (set any coordinate value to null to use size from raw video)
# (set extra_crops to null to ignore it)

# to set a filterspec do this
#
# filterspec:
#   brightness: value in [-1.0, 1.0] (default 0)
#   contrast: value in [-1000.0, 1000.0] (default 1)
#   saturation: value in [0.0, 3.0] (default 1)
#
# (leave off any key above to leave unchanged)
# (set entry to null to do no filtering)
topleft:
  path: ${find_video:${paths.repo},${dataset.name},TL,${dataset.mouse},${dataset.condition},${dataset.run},${dataset.concat_videos},${paths.video_data}}
  crop: [null, null, null, null]
  extra_crops: null
  filterspec: null
topright:
  path: ${find_video:${paths.repo},${dataset.name},TR,${dataset.mouse},${dataset.condition},${dataset.run},${dataset.concat_videos},${paths.video_data}}
  crop: [null, null, null, null]
  extra_crops: null
  filterspec: null
left:
  path: ${find_video:${paths.repo},${dataset.name},L,${dataset.mouse},${dataset.condition},${dataset.run},${dataset.concat_videos},${paths.video_data}}
  crop: [null, null, null, null]
  extra_crops: null
  filterspec: null
right:
  path: ${find_video:${paths.repo},${dataset.name},R,${dataset.mouse},${dataset.condition},${dataset.run},${dataset.concat_videos},${paths.video_data}}
  crop: [null, null, null, null]
  extra_crops: null
  filterspec: null
topcenter:
  path: ${find_video:${paths.repo},${dataset.name},TC,${dataset.mouse},${dataset.condition},${dataset.run},${dataset.concat_videos},${paths.video_data}}
  crop: [null, null, null, null]
  extra_crops: null
  filterspec: null
bottomcenter:
  path: ${find_video:${paths.repo},${dataset.name},BC,${dataset.mouse},${dataset.condition},${dataset.run},${dataset.concat_videos},${paths.video_data}}
  crop: [null, null, null, null]
  extra_crops: null
  filterspec: null
