defaults:
- /labutils/sessionconfig@_here_
- common
- videos: six-cam-view
- videos@calibration: six-cam-view
- metadata: six-cam
- _self_

videos:
  left:
    extra_crops:
      sync_led: [145, 155, 110, 120]

ephys:
  sync_view: left

calibration:
  topleft:
    path: ${find_video:${paths.repo},${dataset.name},TL,all,cal,${dataset.cal_run},${dataset.concat_videos},${paths.video_data}}
  topright:
    path: ${find_video:${paths.repo},${dataset.name},TR,all,cal,${dataset.cal_run},${dataset.concat_videos},${paths.video_data}}
  left:
    path: ${find_video:${paths.repo},${dataset.name},L,all,cal,${dataset.cal_run},${dataset.concat_videos},${paths.video_data}}
  right:
    path: ${find_video:${paths.repo},${dataset.name},R,all,cal,${dataset.cal_run},${dataset.concat_videos},${paths.video_data}}
  topcenter:
    path: ${find_video:${paths.repo},${dataset.name},TC,all,cal,${dataset.cal_run},${dataset.concat_videos},${paths.video_data}}
  bottomcenter:
    path: ${find_video:${paths.repo},${dataset.name},BC,all,cal,${dataset.cal_run},${dataset.concat_videos},${paths.video_data}}

bodyparts:
  nose:
  - nose(bottom)
  - nose(tip)
  - nose(top)
  whiskers(left):
  - pad(top)(left)
  - pad(side)(left)
  - pad(center)
  whiskers(right):
  - pad(top)(right)
  - pad(side)(right)
  - pad(center)
  mouth:
  - lowerlip
  - upperlip(left)
  - upperlip(right)
  eye(left):
  - eye(front)(left)
  - eye(top)(left)
  - eye(back)(left)
  - eye(bottom)(left)
  eye(right):
  - eye(front)(right)
  - eye(top)(right)
  - eye(back)(right)
  - eye(bottom)(right)
  ear(left):
  - ear(base)(left)
  - ear(top)(left)
  - ear(tip)(left)
  - ear(bottom)(left)
  ear(right):
  - ear(base)(right)
  - ear(top)(right)
  - ear(tip)(right)
  - ear(bottom)(right)
  ref:
  - ref(head-post)

cam_bodyparts:
  TL:
  - nose(tip)
  - nose(top)
  - eye(front)(left)
  - eye(back)(left)
  - eye(top)(left)
  - eye(bottom)(left)
  - ear(base)(left)
  - ear(tip)(left)
  - ear(top)(left)
  - ear(bottom)(left)
  TR:
  - nose(tip)
  - nose(top)
  - eye(front)(right)
  - eye(back)(right)
  - eye(top)(right)
  - eye(bottom)(right)
  - ear(base)(right)
  - ear(tip)(right)
  - ear(top)(right)
  - ear(bottom)(right)
  L:
  - lowerlip
  - upperlip(left)
  - nose(bottom)
  - nose(tip)
  - nose(top)
  - pad(top)(left)
  - pad(side)(left)
  - pad(center)
  - eye(front)(left)
  - eye(back)(left)
  - eye(top)(left)
  - eye(bottom)(left)
  - ear(base)(left)
  - ear(tip)(left)
  - ear(top)(left)
  - ear(bottom)(left)
  R:
  - lowerlip
  - upperlip(right)
  - nose(bottom)
  - nose(tip)
  - nose(top)
  - pad(top)(right)
  - pad(side)(right)
  - pad(center)
  - eye(front)(right)
  - eye(back)(right)
  - eye(top)(right)
  - eye(bottom)(right)
  - ear(base)(right)
  - ear(tip)(right)
  - ear(top)(right)
  - ear(bottom)(right)
  TC:
  - nose(tip)
  - nose(top)
  - eye(front)(left)
  - eye(back)(left)
  - eye(top)(left)
  - eye(bottom)(left)
  - eye(front)(right)
  - eye(back)(right)
  - eye(top)(right)
  - eye(bottom)(right)
  BC:
  - lowerlip
  - upperlip(left)
  - upperlip(right)
  - nose(bottom)
  - nose(tip)
  - nose(top)
  - pad(top)(left)
  - pad(top)(right)
  - pad(center)
