defaults:
- main
- _self_

setupproject: false
analyze: false
filter: false
calibrate: false
triangulate: false
filter_3d: false
reproj_3d: false
label_2d: false
label_3d: false
label_combined: false
compare_viz: false
run_data: false
run_viz: false
run_all: false
clean_data: false
clean_viz: false
clean: false
