# defaults:
#   - _self_
#   # - override hydra/hydra_logging: disabled
#   # - override hydra/job_logging: disabled

hydra:
  job:
    chdir: true
  run:
    dir: ./job-output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./job-output/sweep/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  # output_subdir: null

paths:
  repo: ${hydra:runtime.cwd}
  video_data: video-data
  dlc:
    projects: ${paths.repo}/dlc-projects
  anipose: ${paths.repo}/anipose-projects

gpu: 0
ncores: 20
