[project]
name = "cheese3d"
version = "0.1.0"
description = "Sensitive detection and analysis of whole-face movement in mice."
authors = [{ name = "Hou Lab CSHL", email = "the.hou.lab@gmail.com" }]
readme = "../../README.md"
requires-python = "==3.10.*"
scripts = { cheese3d = "cheese3d.cli:cli" }
dependencies = [
    "pip>=25.2,<26",
    "ipython",
    "ipykernel",
    "jupyter",
    "protobuf < 3.20",
    "tables == 3.7.*",
    "pandas == 2.1.*",
    # "numpy == 1.23.2",
    # "numpy == 1.26.1",
    "configobj == 5.0.8",
    "hydra-core",
    "joblib",
    "torch <= 1.12.0",
    # "napari-deeplabcut @ https://github.com/Hou-Lab-CSHL/napari-deeplabcut.git",
    "aniposelib @ https://github.com/Hou-Lab-CSHL/aniposelib.git#jax",
    "anipose @ https://github.com/Hou-Lab-CSHL/anipose.git",
    "opencv-python == 4.7.*",
    "opencv-python-headless == 4.7.*",
    "opencv-contrib-python == 4.7.*",
    # "vtk == 9.3.*",
    # "mayavi == 4.8.2",
    # "av == 9.2.0",
    "pims == 0.6.*",
    "seaborn",
    "open-ephys-python-tools",
    "typer-slim[standard]>=0.15.3,<0.16",
    "textual",
    "textual-dev",
    # "cheese3d-annotator == 0.1.0"
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.metadata]
allow-direct-references = true
